# Generated by Django 3.2.20 on 2023-07-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f7dcf731130> <django.db.models.query_utils.DeferredAttribute object at 0x7f7dcf731190>', max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('approved', models.BooleanField(default=False)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.tables')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.guest')),
            ],
        ),
    ]
