# Generated by Django 3.2.20 on 2023-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='id',
        ),
        migrations.AddField(
            model_name='tables',
            name='table_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f56090758e0> <django.db.models.query_utils.DeferredAttribute object at 0x7f56090756d0>', max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
