# Generated by Django 3.2.20 on 2023-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f633f0d3c40> <django.db.models.query_utils.DeferredAttribute object at 0x7f633f0d3ca0>', max_length=100),
        ),
    ]
