# Generated by Django 3.2.20 on 2023-07-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f96dfbf3f70> <django.db.models.query_utils.DeferredAttribute object at 0x7f96dfbf3fd0>', max_length=100),
        ),
    ]
